### ISSUE TITLE
kitchen-docker fails with "Errno::ENOENT: No such file or directory - /sbin/status"

### ISSUE THREAD

**Issue by StephenKing** [TYPO3-cookbooks/t3-base#1]
Currently, CI builds of _t3-base_ [fail](https://chef-ci.typo3.org/job/TYPO3-cookbooks/job/t3-base/job/master/33/console) with 

> Errno::ENOENT: No such file or directory - /sbin/status

I had this also locally a couple of time locally and was just happy that it works on chef-ci. Now, it doesn't anymore. I've cleared all docker images a couple of days ago, not sure if it was because they're now different from before.

<details>
<summary>Debug logging:</summary>

```         ================================================================================
           Error executing action `restart` on resource 'service[ssh]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - /sbin/status

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/openssh/recipes/default.rb

            61: service 'ssh' do
            62:   service_name node['openssh']['service_name']
            63:   supports value_for_platform_family(
            64:     %w(debian rhel fedora) => [:restart, :reload, :status],
            65:     %w(arch) =>  [:restart],
            66:     'default' => [:restart, :reload]
            67:   )
            68:   action [:enable, :start]
            69: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/openssh/recipes/default.rb:61:in `from_file'

           service("ssh") do
             action [:enable, :start]
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "ssh"
             enabled nil
             running nil
             masked nil
             pattern "ssh"
             declared_type :service
             cookbook_name "openssh"
             recipe_name "default"
           end

>>>> Caused by Errno::ENOENT: No such file or directory - /sbin/status
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/command/unix.rb:105:in `exec'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/command/unix.rb:105:in `block in popen4'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/command/unix.rb:67:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/command/unix.rb:67:in `popen4'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/service/upstart.rb:244:in `upstart_goal_state'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/service/upstart.rb:125:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:128:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:57:in `load'
/opt/chef/bin/chef-client:57:in `<main>'
```
</details>

**Comment by StephenKing** [comment]
The reason for this is that Chef Client picks the wrong provider for the `service[ssh]` resource inside of the docker container.

`/sbin/status` comes from _upstart_ and we can also see in the stack trace that it picked that provider. This is obviously wrong for Debian 8 (Debian 7 isn't affected by that bug).

Instead, it should pick SysVinit, which is implemented by [`Chef::Provider::Service::Init::Debian`](https://docs.chef.io/resource_service.html).

**Comment by StephenKing** [comment]
The detection of available providers is in [`chef/platform/service_helpers`](https://github.com/chef/chef/blob/12.5-stable/lib/chef/platform/service_helpers.rb#L45-L74):

- /usr/sbin/update-rc.d exists -> debian
- /usr/sbin/invoke-rc.d exists -> invokercd
- /sbin/insserv exists -> insserv
- /sbin/start DOES NOT exists -> NO upstart.. - WTF?
 - /proc/1/comm outputs `systemd` -> systemd

So we have kind of all init systems available, except `upstart`. But this one is picked.

**Comment by StephenKing** [comment]
As remediation, we can override the provider for the `service[ssh]` resource in `t3-base` as follows:

    resources('service[ssh]').provider Chef::Provider::Service::Init::Debian

**Comment by StephenKing** [comment]
Similar issue was chef-cookbooks/openssh#60, which was, however, caused by hard-coding the provider for various Ubuntu versions.

**Comment by StephenKing** [comment]
👎  to this.

I would prefer TYPO3-infrastructure/jenkins-pipeline-global-library-chefci#14 instead.

**Comment by StephenKing** [comment]
fixed by switching to a different technology. always solves all problems.
